import os
import requests
import tempfile
from fpdf import FPDF
from dotenv import load_dotenv

load_dotenv()

# Centralized Plan Configuration
PLANS = {
    "single": {
        "price": 99,
        "credits": 1,
        "alert_tier": "free",
        "description": "1 Tender Analysis",
        "expiry_days": None
    },
    "pack": {
        "price": 399,
        "credits": 5,
        "alert_tier": "basic",
        "description": "5 Tender Pack",
        "expiry_days": 60
    },
    "monthly": {
        "price": 799,
        "credits": 30, # Soft limit
        "alert_tier": "full",
        "description": "Monthly Pro (30 Analyses)",
        "expiry_days": 30
    }
}

def format_inr(amount: int) -> str:
    """Formats amount in Indian style: 50,00,000 → ₹50 Lakhs"""
    if amount >= 10000000:
        return f"₹{amount / 10000000:.1f} Crores"
    elif amount >= 100000:
        return f"₹{amount / 100000:.1f} Lakhs"
    elif amount >= 1000:
        return f"₹{amount / 1000:.0f}K"
    else:
        return f"₹{amount}"

def detect_language(text: str) -> str:
    """Detects the language of the incoming message. Defaults to Hinglish."""
    if not text:
        return "Hinglish"
    
    text_lower = text.lower().strip()
    
    if any(word in text_lower for word in ["english", "eng"]):
        return "English"
    if any(word in text_lower for word in ["hindi"]):
        return "Hindi"
    if any(word in text_lower for word in ["marathi", "aahe", "kasa ahe"]):
        return "Marathi"
    if any(word in text_lower for word in ["gujarati", "kem cho"]):
        return "Gujarati"
    if any(word in text_lower for word in ["tamil", "vanakkam", "eppadi"]):
        return "Tamil"
    if any(word in text_lower for word in ["telugu", "namaskaram", "ela unnaru"]):
        return "Telugu"
    if any(word in text_lower for word in ["kya", "hai", "kaise", "bhejo", "bhai", "karo", "chahiye", "dekho", "batao"]):
        return "Hinglish"
    
    return "Hinglish"

class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "TenderBot - AI Analysis Report", align="C", ln=True)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, "Generated by TenderBot - AI analysis for guidance only. Please read original documents.", align="C")

def safe_text(text):
    """Convert text to ASCII-safe version with emoji-to-text conversion."""
    if not isinstance(text, str):
        text = str(text)
    cleaned = ""
    for char in text:
        if ord(char) < 128:
            cleaned += char
        elif char == '₹':
            cleaned += 'Rs.'
        elif char in ('→', '➡'):
            cleaned += '->'
        elif char in ('✅', '☑'):
            cleaned += '[OK]'
        elif char in ('❌', '✗'):
            cleaned += '[X]'
        elif char in ('⚠', '\u26a0'):
            cleaned += '[!]'
        elif char == '🔴':
            cleaned += '[HIGH]'
        elif char == '🟡':
            cleaned += '[MED]'
        elif char == '🟢':
            cleaned += '[LOW]'
        elif char == '🏆':
            cleaned += '[VERDICT]'
        elif char in ('📋', '📄', '📊', '💰', '🎯', '⏰', '🏗', '📦', '📍'):
            cleaned += ''
        else:
            cleaned += '?'
    return cleaned


def generate_pdf_report(analysis_json: dict, phone_number: str) -> bytes:
    """Generates a formatted PDF report from the analysis JSON. Returns bytes."""
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)

    # Header info
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"Report for: {phone_number}", ln=True)
    
    # Quick verdict at top
    verdict = analysis_json.get("quick_verdict_recommendation", "")
    score = analysis_json.get("quick_verdict_score", "N/A")
    if verdict:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, safe_text(f"VERDICT: {score}/10 - {verdict}"), ln=True)
    
    # Tender info
    pdf.set_font("Helvetica", size=10)
    for field, label in [("department", "Department"), ("value", "Value"), 
                          ("deadline_date", "Deadline"), ("location", "Location")]:
        val = analysis_json.get(field, "N/A")
        if field == "value" and isinstance(val, (int, float)) and val > 0:
            val = f"Rs. {val:,.0f}"
        pdf.cell(0, 7, safe_text(f"{label}: {val}"), ln=True)
    pdf.ln(5)

    parts_to_include = [
        ("PART 1 - TENDER SUMMARY", "part1_summary"),
        ("PART 2 - ELIGIBILITY CHECK", "part2_eligibility"),
        ("PART 3 - HIDDEN RISKS", "part3_risks"),
        ("PART 4 - BOQ RATES & BID STRATEGY", "part4_boq"),
        ("PART 5 - ACTION PLAN", "part5_action_plan"),
        ("PART 6 - PROJECT COST ESTIMATE", "part6_cost_estimate"),
        ("PART 7 - COMPETITOR INTELLIGENCE", "part7_competitor"),
        ("PART 8 - SUBCONTRACTORS", "part8_subcontractors"),
        ("PART 9 - CASH FLOW", "part9_cashflow"),
        ("FINAL VERDICT", "part10_recommendation")
    ]

    for title, key in parts_to_include:
        content = analysis_json.get(key, "Information not available")
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, safe_text(title), ln=True)
        pdf.set_font("Helvetica", size=10)
        pdf.multi_cell(0, 5, txt=safe_text(str(content)))
        pdf.ln(3)

    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(0, 5, "DISCLAIMER: This is AI-generated analysis for guidance only. Always read the original tender document before making any decisions.")

    return bytes(pdf.output())
