import os
import requests
import tempfile
from fpdf import FPDF
from dotenv import load_dotenv

load_dotenv()

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")

def download_twilio_media(media_url: str) -> str:
    """Downloads media from Twilio to a temporary file."""
    response = requests.get(media_url, auth=(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN))
    if response.status_code == 200:
        fd, temp_path = tempfile.mkstemp(suffix=".pdf")
        with os.fdopen(fd, 'wb') as f:
            f.write(response.content)
        return temp_path
    raise Exception(f"Failed to download media: {response.status_code}")

def detect_language(text: str) -> str:
    """Detects the language of the incoming message and maps to a supported language.
    Defaulting to Hinglish if ambiguous."""
    text_lower = text.lower()
    
    if any(word in text_lower for word in ["namaste", "hai", "kya", "kaise", "bhejo"]):
        return "Hinglish"
    if any(word in text_lower for word in ["marathi", "aahe", "kasa", "ahe"]):
        return "Marathi"
    if any(word in text_lower for word in ["gujarati", "kem", "cho", "che"]):
        return "Gujarati"
    if any(word in text_lower for word in ["tamil", "eppadi", "irukke", "vanakkam"]):
        return "Tamil"
    if any(word in text_lower for word in ["telugu", "ela", "unnaru", "namaskaram"]):
        return "Telugu"
    if any(word in text_lower for word in ["hi", "hello", "what", "is", "this", "english"]):
        return "English"
    
    # Default to Hinglish for Indian contractors if not fully clear
    return "Hinglish"

class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "TenderBot - AI Analysis Report", align="C", ln=True)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, "Generated by TenderBot - AI analysis for guidance only. Please read original documents.", align="C")

def generate_pdf_report(analysis_json: dict, phone_number: str) -> str:
    """Generates a formatted PDF report from the analysis JSON."""
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)
    
    # Ensure all text is casted to ASCII/latin-1 roughly to prevent FPDF unicode errors unless we add a unicode font
    def safe_text(text):
        if not isinstance(text, str):
            text = str(text)
        return text.encode('latin-1', 'replace').decode('latin-1')

    # Basic Info
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"Contractor Phone: {phone_number}", ln=True)
    pdf.ln(5)

    parts_to_include = [
        ("PART 1 - TENDER SUMMARY", "part1_summary"),
        ("PART 2 - ELIGIBILITY CHECK", "part2_eligibility"),
        ("PART 3 - HIDDEN RISKS", "part3_risks"),
        ("PART 4 - BOQ RATES & BID STRATEGY", "part4_boq"),
        ("PART 5 - ACTION PLAN", "part5_action_plan"),
        ("PART 6 - PROJECT COST ESTIMATE", "part6_cost_estimate"),
        ("PART 7 - COMPETITOR INTELLIGENCE", "part7_competitor"),
        ("PART 8 - SUBCONTRACTORS", "part8_subcontractors"),
        ("PART 9 - CASH FLOW", "part9_cashflow"),
        ("FINAL VERDICT", "part10_recommendation")
    ]
    
    for title, key in parts_to_include:
        content = analysis_json.get(key, "Information not available")
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, safe_text(title), ln=True)
        pdf.set_font("Helvetica", size=11)
        pdf.multi_cell(0, 6, txt=safe_text(content))
        pdf.ln(5)

    fd, temp_path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)
    pdf.output(temp_path)
    return temp_path
